#
# Copyright (c) 2026      Nanook Consulting  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

headers += \
        base/base.h

libdschedmca_dlog_la_SOURCES += \
        base/log_base_select.c \
        base/log_base_frame.c
