/*
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2017      Intel, Inc.  All rights reserved.
 * Copyright (c) 2021-2026 Nanook Consulting  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef DSCHED_DL_LIBLTDL
#define DSCHED_DL_LIBLTDL

#include "dsched_config.h"

#include "src/mca/ddl/ddl.h"

#include <ltdl.h>

DSCHED_DECLSPEC extern dsched_ddl_base_module_t dsched_ddl_plibltddl_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct dsched_ddl_handle_t {
    lt_dlhandle ltddl_handle;
#if DSCHED_ENABLE_DEBUG
    char *filename;
#endif
};

typedef struct {
    dsched_ddl_base_component_t base;

#if DSCHED_DDL_DLIBLTDL_HAVE_LT_DLADVISE
    /* If the version of plibltdl that we are compiling against has
       lt_dladvise, use it to support opening DSOs in a variety of
       modes. */
    lt_dladvise advise_private_noext;
    lt_dladvise advise_private_ext;
    lt_dladvise advise_public_noext;
    lt_dladvise advise_public_ext;
#endif
} dsched_ddl_plibltddl_component_t;

DSCHED_DECLSPEC extern dsched_ddl_plibltddl_component_t dsched_mca_ddl_plibltddl_component;

#endif /* DSCHED_DL_LIBLTDL */
