/*
 * Copyright (c) 2015     Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2016-2020 Intel, Inc.  All rights reserved.
 * Copyright (c) 2022-2026 Nanook Consulting  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef DSCHED_PDL_PDLOPEN
#define DSCHED_PDL_PDLOPEN

#include "src/include/dsched_config.h"

#include "src/mca/ddl/ddl.h"

extern dsched_ddl_base_module_t dsched_ddl_ddlopen_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct dsched_ddl_handle_t {
    void *dlopen_handle;
#if DSCHED_ENABLE_DEBUG
    void *filename;
#endif
};

typedef struct {
    dsched_ddl_base_component_t base;

    char *filename_suffixes_mca_storage;
    char **filename_suffixes;
} dsched_ddl_ddlopen_component_t;

extern dsched_ddl_ddlopen_component_t dsched_mca_ddl_ddlopen_component;

#endif /* DSCHED_PDL_PDLOPEN */
