/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2006 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * Copyright (c) 2014      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * Copyright (c) 2015-2019 Intel, Inc.  All rights reserved.
 * Copyright (c) 2020      Cisco Systems, Inc.  All rights reserved
 * Copyright (c) 2021-2026 Nanook Consulting  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef DSCHED_CONSTANTS_H
#define DSCHED_CONSTANTS_H

#include "dsched_config.h"

BEGIN_C_DECLS

#define DSCHED_ERR_BASE  0
#define DSCHED_ERR_SPLIT 100

enum {
    /* Error codes inherited from DSCHED.  Still enum values so that we
       get the nice debugger help. */

    DSCHED_SUCCESS = (DSCHED_ERR_BASE),

    DSCHED_ERROR = (DSCHED_ERR_BASE - 1),
    DSCHED_ERR_OUT_OF_RESOURCE = (DSCHED_ERR_BASE - 2),      /* fatal error */
    DSCHED_ERR_TEMP_OUT_OF_RESOURCE = (DSCHED_ERR_BASE - 3), /* try again later */
    DSCHED_ERR_RESOURCE_BUSY = (DSCHED_ERR_BASE - 4),
    DSCHED_ERR_BAD_PARAM = (DSCHED_ERR_BASE - 5),
    DSCHED_ERR_FATAL = (DSCHED_ERR_BASE - 6),
    DSCHED_ERR_NOT_IMPLEMENTED = (DSCHED_ERR_BASE - 7),
    DSCHED_ERR_NOT_SUPPORTED = (DSCHED_ERR_BASE - 8),
    DSCHED_ERR_INTERRUPTED = (DSCHED_ERR_BASE - 9),
    DSCHED_ERR_WOULD_BLOCK = (DSCHED_ERR_BASE - 10),
    DSCHED_ERR_IN_ERRNO = (DSCHED_ERR_BASE - 11),
    DSCHED_ERR_UNREACH = (DSCHED_ERR_BASE - 12),
    DSCHED_ERR_NOT_FOUND = (DSCHED_ERR_BASE - 13),
    DSCHED_EXISTS = (DSCHED_ERR_BASE - 14), /* indicates that the specified object already exists */
    DSCHED_ERR_TIMEOUT = (DSCHED_ERR_BASE - 15),
    DSCHED_ERR_NOT_AVAILABLE = (DSCHED_ERR_BASE - 16),
    DSCHED_ERR_PERM = (DSCHED_ERR_BASE - 17), /* no permission */
    DSCHED_ERR_VALUE_OUT_OF_BOUNDS = (DSCHED_ERR_BASE - 18),
    DSCHED_ERR_FILE_READ_FAILURE = (DSCHED_ERR_BASE - 19),
    DSCHED_ERR_FILE_WRITE_FAILURE = (DSCHED_ERR_BASE - 20),
    DSCHED_ERR_FILE_OPEN_FAILURE = (DSCHED_ERR_BASE - 21),
    DSCHED_ERR_PACK_MISMATCH = (DSCHED_ERR_BASE - 22),
    DSCHED_ERR_PACK_FAILURE = (DSCHED_ERR_BASE - 23),
    DSCHED_ERR_UNPACK_FAILURE = (DSCHED_ERR_BASE - 24),
    DSCHED_ERR_UNPACK_INADEQUATE_SPACE = (DSCHED_ERR_BASE - 25),
    DSCHED_ERR_UNPACK_READ_PAST_END_OF_BUFFER = (DSCHED_ERR_BASE - 26),
    DSCHED_ERR_TYPE_MISMATCH = (DSCHED_ERR_BASE - 27),
    DSCHED_ERR_OPERATION_UNSUPPORTED = (DSCHED_ERR_BASE - 28),
    DSCHED_ERR_UNKNOWN_DATA_TYPE = (DSCHED_ERR_BASE - 29),
    DSCHED_ERR_BUFFER = (DSCHED_ERR_BASE - 30),
    DSCHED_ERR_DATA_TYPE_REDEF = (DSCHED_ERR_BASE - 31),
    DSCHED_ERR_DATA_OVERWRITE_ATTEMPT = (DSCHED_ERR_BASE - 32),
    DSCHED_ERR_MODULE_NOT_FOUND = (DSCHED_ERR_BASE - 33),
    DSCHED_ERR_TOPO_SLOT_LIST_NOT_SUPPORTED = (DSCHED_ERR_BASE - 34),
    DSCHED_ERR_TOPO_SOCKET_NOT_SUPPORTED = (DSCHED_ERR_BASE - 35),
    DSCHED_ERR_TOPO_CORE_NOT_SUPPORTED = (DSCHED_ERR_BASE - 36),
    DSCHED_ERR_NOT_ENOUGH_SOCKETS = (DSCHED_ERR_BASE - 37),
    DSCHED_ERR_NOT_ENOUGH_CORES = (DSCHED_ERR_BASE - 38),
    DSCHED_ERR_INVALID_PHYS_CPU = (DSCHED_ERR_BASE - 39),
    DSCHED_ERR_MULTIPLE_AFFINITIES = (DSCHED_ERR_BASE - 40),
    DSCHED_ERR_SLOT_LIST_RANGE = (DSCHED_ERR_BASE - 41),
    DSCHED_ERR_NETWORK_NOT_PARSEABLE = (DSCHED_ERR_BASE - 42),
    DSCHED_ERR_SILENT = (DSCHED_ERR_BASE - 43),
    DSCHED_ERR_NOT_INITIALIZED = (DSCHED_ERR_BASE - 44),
    DSCHED_ERR_NOT_BOUND = (DSCHED_ERR_BASE - 45),
    DSCHED_ERR_TAKE_NEXT_OPTION = (DSCHED_ERR_BASE - 46),
    DSCHED_ERR_PROC_ENTRY_NOT_FOUND = (DSCHED_ERR_BASE - 47),
    DSCHED_ERR_DATA_VALUE_NOT_FOUND = (DSCHED_ERR_BASE - 48),
    DSCHED_ERR_CONNECTION_FAILED = (DSCHED_ERR_BASE - 49),
    DSCHED_ERR_AUTHENTICATION_FAILED = (DSCHED_ERR_BASE - 50),
    DSCHED_ERR_COMM_FAILURE = (DSCHED_ERR_BASE - 51),
    DSCHED_ERR_SERVER_NOT_AVAIL = (DSCHED_ERR_BASE - 52),
    DSCHED_ERR_IN_PROCESS = (DSCHED_ERR_BASE - 53),
    DSCHED_OPERATION_SUCCEEDED = (DSCHED_ERR_BASE - 72),

    /* error codes specific to DSCHED - don't forget to update
        src/util/error_strings.c when adding new error codes!!
        Otherwise, the error reporting system will potentially crash,
        or at the least not be able to report the new error correctly.
     */

    DSCHED_ERR_RECV_LESS_THAN_POSTED = (DSCHED_ERR_SPLIT - 1),
    DSCHED_ERR_RECV_MORE_THAN_POSTED = (DSCHED_ERR_SPLIT - 2),
    DSCHED_ERR_NO_MATCH_YET = (DSCHED_ERR_SPLIT - 3),
    DSCHED_ERR_REQUEST = (DSCHED_ERR_SPLIT - 4),
    DSCHED_ERR_NO_CONNECTION_ALLOWED = (DSCHED_ERR_SPLIT - 5),
    DSCHED_ERR_CONNECTION_REFUSED = (DSCHED_ERR_SPLIT - 6),
    DSCHED_ERR_COMPARE_FAILURE = (DSCHED_ERR_SPLIT - 9),
    DSCHED_ERR_COPY_FAILURE = (DSCHED_ERR_SPLIT - 10),
    DSCHED_ERR_PROC_STATE_MISSING = (DSCHED_ERR_SPLIT - 11),
    DSCHED_ERR_PROC_EXIT_STATUS_MISSING = (DSCHED_ERR_SPLIT - 12),
    DSCHED_ERR_INDETERMINATE_STATE_INFO = (DSCHED_ERR_SPLIT - 13),
    DSCHED_ERR_NODE_FULLY_USED = (DSCHED_ERR_SPLIT - 14),
    DSCHED_ERR_INVALID_NUM_PROCS = (DSCHED_ERR_SPLIT - 15),
    DSCHED_ERR_ADDRESSEE_UNKNOWN = (DSCHED_ERR_SPLIT - 16),
    DSCHED_ERR_SYS_LIMITS_PIPES = (DSCHED_ERR_SPLIT - 17),
    DSCHED_ERR_PIPE_SETUP_FAILURE = (DSCHED_ERR_SPLIT - 18),
    DSCHED_ERR_SYS_LIMITS_CHILDREN = (DSCHED_ERR_SPLIT - 19),
    DSCHED_ERR_FAILED_GET_TERM_ATTRS = (DSCHED_ERR_SPLIT - 20),
    DSCHED_ERR_WDIR_NOT_FOUND = (DSCHED_ERR_SPLIT - 21),
    DSCHED_ERR_EXE_NOT_FOUND = (DSCHED_ERR_SPLIT - 22),
    DSCHED_ERR_PIPE_READ_FAILURE = (DSCHED_ERR_SPLIT - 23),
    DSCHED_ERR_EXE_NOT_ACCESSIBLE = (DSCHED_ERR_SPLIT - 24),
    DSCHED_ERR_FAILED_TO_START = (DSCHED_ERR_SPLIT - 25),
    DSCHED_ERR_FILE_NOT_EXECUTABLE = (DSCHED_ERR_SPLIT - 26),
    DSCHED_ERR_HNP_COULD_NOT_START = (DSCHED_ERR_SPLIT - 27),
    DSCHED_ERR_SYS_LIMITS_SOCKETS = (DSCHED_ERR_SPLIT - 28),
    DSCHED_ERR_SOCKET_NOT_AVAILABLE = (DSCHED_ERR_SPLIT - 29),
    DSCHED_ERR_SYSTEM_WILL_BOOTSTRAP = (DSCHED_ERR_SPLIT - 30),
    DSCHED_ERR_RESTART_LIMIT_EXCEEDED = (DSCHED_ERR_SPLIT - 31),
    DSCHED_ERR_INVALID_NODE_RANK = (DSCHED_ERR_SPLIT - 32),
    DSCHED_ERR_INVALID_LOCAL_RANK = (DSCHED_ERR_SPLIT - 33),
    DSCHED_ERR_UNRECOVERABLE = (DSCHED_ERR_SPLIT - 34),
    DSCHED_ERR_MEM_LIMIT_EXCEEDED = (DSCHED_ERR_SPLIT - 35),
    DSCHED_ERR_HEARTBEAT_LOST = (DSCHED_ERR_SPLIT - 36),
    DSCHED_ERR_PROC_STALLED = (DSCHED_ERR_SPLIT - 37),
    DSCHED_ERR_NO_APP_SPECIFIED = (DSCHED_ERR_SPLIT - 38),
    DSCHED_ERR_NO_EXE_SPECIFIED = (DSCHED_ERR_SPLIT - 39),
    DSCHED_ERR_COMM_DISABLED = (DSCHED_ERR_SPLIT - 40),
    DSCHED_ERR_FAILED_TO_MAP = (DSCHED_ERR_SPLIT - 41),
    DSCHED_ERR_SENSOR_LIMIT_EXCEEDED = (DSCHED_ERR_SPLIT - 42),
    DSCHED_ERR_ALLOCATION_PENDING = (DSCHED_ERR_SPLIT - 43),
    DSCHED_ERR_NO_PATH_TO_TARGET = (DSCHED_ERR_SPLIT - 44),
    DSCHED_ERR_OP_IN_PROGRESS = (DSCHED_ERR_SPLIT - 45),
    DSCHED_ERR_OPEN_CONDUIT_FAIL = (DSCHED_ERR_SPLIT - 46),
    DSCHED_ERR_DUPLICATE_MSG = (DSCHED_ERR_SPLIT - 47),
    DSCHED_ERR_OUT_OF_ORDER_MSG = (DSCHED_ERR_SPLIT - 48),
    DSCHED_ERR_FORCE_SELECT = (DSCHED_ERR_SPLIT - 49),
    DSCHED_ERR_JOB_CANCELLED = (DSCHED_ERR_SPLIT - 50),
    DSCHED_ERR_CONDUIT_SEND_FAIL = (DSCHED_ERR_SPLIT - 51),
    DSCHED_ERR_NOMEM = (DSCHED_ERR_SPLIT - 52)
};

#define DSCHED_ERR_MAX (DSCHED_ERR_SPLIT + 100)

END_C_DECLS

#endif /* DSCHED_CONSTANTS_H */
